"""Registro único de códigos observables: UI y canarios, sin IO ni cuentas.

Los emisores deben usar códigos de PROVIDER_ALERT_CODES y el panel añade
solo categorías locales conocidas; nunca imprimir códigos arbitrarios del CSV.
"""
PROVIDER_ALERT_CODES = frozenset({
    "BREAKER_INVALIDO", "BREAKER_REVISION_MANUAL", "QUEJA_EXTERNA_REVISAR",
    "CORTACIRCUITOS_ABIERTO", "COLA_INVALIDA", "TRABAJADOR_PARADO",
    "COLA_CORRUPTA_RECUPERADA", "REGISTRO_EVENTOS_COLA_INACCESIBLE",
    "REGISTRO_INVALIDO", "RONDA_PARCIAL", "ERRORES_SEGUIDOS",
    "SIN_CONFIRMACIONES", "SIN_RONDAS_ESPERADAS", "FALLO_PLAN_REPETIDO",
    "CAIDA_RENDIMIENTO_SOSTENIDA",
})

PANEL_LOCAL_CODES = frozenset({
    "CANARIO_NO_RECONOCIDO", "CANARIOS_NO_DISPONIBLES",
    "TIKTOK_ESTADO_SEGURIDAD_INVALIDO", "TIKTOK_ESCRITURA_BLOQUEADA",
    "TIKTOK_SEGUIR_EN_DESCANSO", "REGISTRO_RONDAS_INVALIDO",
    "REGISTRO_RONDAS_AUSENTE",
})

ALERT_CODES = PROVIDER_ALERT_CODES | PANEL_LOCAL_CODES

# No reducir el conjunto histórico de bloqueos del panel.
BLOCKING_CODES = frozenset({
    "BREAKER_REVISION_MANUAL", "QUEJA_EXTERNA_REVISAR",
    "CORTACIRCUITOS_ABIERTO", "TIKTOK_ESCRITURA_BLOQUEADA",
})
